#config.py

from datetime import date, datetime

# === KEY CYCLE DATES ===
# Halvings
LAST_HALVING = date(2024, 4, 20)
NEXT_HALVING = date(2028, 4, 20)

# Forecasted cycle dates
CYCLE_PEAK = date(2025, 10, 11)
CYCLE_BOTTOM = date(2026, 10, 30)

# === HISTORICAL DATES ===
# Previous cycle peak
PREVIOUS_CYCLE_PEAK = datetime(2021, 11, 10)

# Historical cycle bottom
CYCLE_BOTTOM_DATE = datetime(2022, 11, 22)

# === FORECASTED DATES (datetime) ===
FORECAST_PEAK_DATE = datetime(2025, 10, 15)
FORECAST_BOTTOM_DATE = datetime(2026, 10, 30)

# === PRICES ===
# Historical prices
BOTTOM_PRICE = 15700
PEAK_PRICE = None  # not known yet

# Forecasted prices
FORECAST_PEAK_PRICE = 200000
FORECAST_BOTTOM_PRICE = 75000

# === API SETTINGS ===
BINANCE_URL = "https://api.binance.com/api/v3/klines"
SYMBOL = "BTCUSDT"
INTERVAL = "1d"
LIMIT = 366

# === CYCLE PHASES (days from bottom) ===
PHASE_ACCUMULATION_START = 0
PHASE_ACCUMULATION_END = 180
PHASE_PARABOLIC_START = 180
PHASE_PARABOLIC_END = 730
PHASE_DISTRIBUTION_START = 730
PHASE_DISTRIBUTION_END = 1000
PHASE_CAPITULATION_START = 1000
PHASE_CAPITULATION_END = 1460

# Export constants
__all__ = [
    'LAST_HALVING', 'NEXT_HALVING', 'CYCLE_PEAK', 'CYCLE_BOTTOM',
    'PREVIOUS_CYCLE_PEAK', 'CYCLE_BOTTOM_DATE', 'FORECAST_PEAK_DATE', 'FORECAST_BOTTOM_DATE',
    'BOTTOM_PRICE', 'PEAK_PRICE', 'FORECAST_PEAK_PRICE', 'FORECAST_BOTTOM_PRICE',
    'BINANCE_URL', 'SYMBOL', 'INTERVAL', 'LIMIT',
    'PHASE_ACCUMULATION_START', 'PHASE_ACCUMULATION_END',
    'PHASE_PARABOLIC_START', 'PHASE_PARABOLIC_END',
    'PHASE_DISTRIBUTION_START', 'PHASE_DISTRIBUTION_END',
    'PHASE_CAPITULATION_START', 'PHASE_CAPITULATION_END'
]
